name: BeaconLabsSurvival
version: '1.0.0'
main: org.bcnlab.beaconLabsSurvival.BeaconLabsSurvival
api-version: '1.21'
load: STARTUP
authors: [ Vincent Wackler ]
website: bcnlab.org
commands:
    labssurvival:
        description: 'Core info command'
        usage: '/labssurvival'
        aliases: [ beaconlabssurvival ]
